[package]
name = "llvm-cov-async-closure"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = { version = "2.3.0" }
futures = { version = "0.3.31" }
tokio = { version = "1.40.0", features = ["full"] }
